name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Configure Git with PAT
        env:
          GITHUB_PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "https://${GITHUB_PAT}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_DNS }} '
            # Navigate to the project directory and perform Git operations
            cd /home/ubuntu/backend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart your-app-service
          '
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
