name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          GITHUB_PAT: ${{ secrets.GIT_PAT }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_DNS }} '
            git config --global credential.helper "store"
            echo "https://${GITHUB_PAT}:x-oauth-basic@github.com" > ~/.git-credentials

            cd /home/ubuntu/backend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart your-app-service
            '
